#!/bin/bash

# usage mv-sed expression files


function usage() {
  echo "-h	Print this message."
  echo "-f	Move the files, without this flag changed filenames are printed."
  echo "-s	Sed expression."
}

# Defaults
dry_run=1

eval set -- $(getopt -n $0 -o "-s:fh" -- "$@")

declare -a files

while [ $# -gt 0 ] ; do
        case "$1" in
                -f) dry_run=0 ; shift ;;
                -s) expression=$2 ; shift 2;;
                -h) usage; exit;;
                --) shift ;;
                -*) echo "bad option '$1'" ; exit 1 ;;
                *) files=("${files[@]}" "$1") ; shift ;;
         esac
done

for filename in "${files[@]}"; do
  if [ $dry_run = 1 ]; then
    echo "$filename" "->" "$(echo "$filename" | sed -s "$expression")"
  else
    echo "$filename" "->" "$(echo "$filename" | sed -s "$expression")"
    mv "$filename" "$(echo "$filename" | sed -s "$expression")"
  fi
done
